name: applicant_quest
description: Приложение для квеста абитуриентов
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.1
  cloud_firestore: ^4.15.2
  firebase_messaging: ^14.7.10
  
  # State Management
  provider: ^6.1.1
  
  # UI
  intl: ^0.18.1
  
  # HTTP
  http: ^0.13.6

flutter:
  uses-material-design: true
  assets:
    - assets/